### ISSUE TITLE
Server Save

### ISSUE THREAD

**Issue by mcao** [LyricLy/Lyric-Selfbot-Cogs#9]
- Ask for confirmation when restoring server if there are already people/messages/channels in the server.
- Account for channel categories.

**Comment by architdate** [comment]
Just finished the second one

**Comment by LyricLy** [comment]
I see no need to ask for confirmation. It makes sense to ask for confirmation for something you can click or a button you can push, because it's possible to click/push by accident. But it's impossible to accidentally type out a long command.
